# pq configuration file
# Copy this file to ~/.config/pq/config.toml or ./.pq.toml

[theme]
# Choose from the following themes:
# atom-one-dark, atom-one-light, catppuccin-latte, catppuccin-mocha,
# dracula, flexoki, gruvbox, monokai, nord, rose-pine,
# rose-pine-dawn, rose-pine-moon, solarized-dark, solarized-light,
# textual-ansi, textual-dark, textual-light, tokyo-night

name = "dracula"
